### ISSUE TITLE
Copy for connect modal

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#159]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/72288205-7899-48f6-b82f-df126bbfac3e)

**Comment by scottrepreneur** [comment]
You're not connected here it looks like. Can you confirm repro steps and provide a link here.

**Comment by benedictvscriticus** [comment]
This is the app link https://smart-invoice-dapp-git-154-dapp-refactor-23-smart-invoice.vercel.app/invoices. I've recorded a loom to show you the issue and describe the expected behaviour.

https://www.loom.com/share/e72b6e9361a74e8ab6ca8e48ca0a8c25?sid=741ce40d-7ca0-4215-8fee-cab0467b4e40

**Comment by scottrepreneur** [comment]
Ah bad copy 👍
