### ISSUE TITLE
Add token name to token dropdown

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#161]
Add token name to this dropdown with the symbol in parens `Wrapped Ether (WETH)`

---

- make wrapped native assets chain dependent
- What is ITT token?
- Can people add their custom token?

![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/c325392f-29bd-4a9c-b241-8ca50414a453)

**Comment by benedictvscriticus** [comment]
This is the app link https://smart-invoice-dapp-git-154-dapp-refactor-23-smart-invoice.vercel.app/invoices. I've recorded a loom to show you the issue and describe the expected behaviour.

https://www.loom.com/share/e72b6e9361a74e8ab6ca8e48ca0a8c25?sid=741ce40d-7ca0-4215-8fee-cab0467b4e40

**Comment by memosys** [comment]
this cannot be solved untill we update the token lists! 
currently tokenlist don't have token name- https://smart-invoice.infura-ipfs.io/ipfs/QmSqhPHwiJnjsbfmrrENGU1GrggVJ9vijMaZquR9ujUW4C

recommend using https://tokenlists.org/ standard which includes token name
