### ISSUE TITLE
Why is the token amount not adding up?

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#162]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/6f88507b-e38a-4a60-9432-3763cf02719c)

**Comment by scottrepreneur** [comment]
This is a classic wei math issue. Doesn't happen with whole numbers. Thanks for finding.

**Comment by benedictvscriticus** [comment]
starting at 4 decimals and three milestones
