### ISSUE TITLE
I cannot create an invoice when having a link included in the project details.

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#163]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/5323daee-3a3e-452b-a445-68a545dc9186)

**Comment by scottrepreneur** [comment]
Initially, this was an issue with the environment variables needed for IPFS pinning. It does look like there's an issue when you try to submit a link, but you should be able to create one without a link since it's optional (to get unblocked in testing here).

**Comment by scottrepreneur** [comment]
Can we confirm this is still an issue with standard escrows?

**Comment by benedictvscriticus** [comment]
Creating escrow with link works now.
