### ISSUE TITLE
Cannot create instant invoice

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#164]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/eb2a102f-201c-4bbf-bce7-00cc790af627)

**Comment by benedictvscriticus** [comment]
This issue persists even when not including a link in the project description @scottrepreneur.

**Comment by scottrepreneur** [comment]
Sorry, yes might still be expected on instant invoice. That was what I was fixing when I borked the subgraph and haven't gotten to revisit it again. Should be nearly there.

**Comment by memosys** [comment]
@scottrepreneur this should be in TODO? I didnt work on this yet!

**Comment by benedictvscriticus** [comment]
@memosys @scottrepreneur still does not work on xDAI

![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/8bfee77e-72ee-4473-9329-a94735225b39)

**Comment by benedictvscriticus** [comment]
all gg - works

![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/c5b78d4b-110b-449b-a8a2-702260073ad9)
