### ISSUE TITLE
Integrate Sepolia because Goerli is being deprecated

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#165]

**Comment by scottrepreneur** [comment]
Out of scope for this (very short) cycle, but yes

**Comment by benedictvscriticus** [comment]
> Out of scope for this (very short) cycle, but yes

Labelled won't fix for now, but should be picked up in a future cycle

**Comment by dan13ram** [comment]
fixed
