### ISSUE TITLE
Infinite load after invoice is created

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#166]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/ba8889f1-28ad-40e5-9884-e5375518bccf)

**Comment by memosys** [comment]
This resolved instantly for me on `goerli` will test gnosis also to be safe

**Comment by memosys** [comment]
just test; issue exists on gnosis!

**Comment by memosys** [comment]
handling this via not redirecting to `newly` created invoice page; 
putting a success page in middle
