### ISSUE TITLE
[UX] Confirmation button becomes clickable again after invoice has been created and before detail page of invoice is loading

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#168]
https://www.loom.com/share/b5acc2217e6c4a2fb57116ffe3b56050?sid=e2e1ab1b-487c-4b4f-b098-49d52b486bfa

**Comment by scottrepreneur** [comment]
just for a second, so won't fix here if we can get the redirect & loading actually working (probably the bigger issue here). if we resort to the modal we can make sure it doesn't get re-enabled.
