### ISSUE TITLE
Improve error handling when client does not have sufficient funds for making deposit to invoice

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#169]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/1118c16e-b34c-4e5a-a0b4-1eefcfe521d7)

**Comment by scottrepreneur** [comment]
You don't have enough WETH here. Can you wrap a bit? We could enhance the error handling here tho.

**Comment by benedictvscriticus** [comment]
> You don't have enough WETH here. Can you wrap a bit? We could enhance the error handling here tho.

After getting WETH I can deposit as expected.

**Comment by memosys** [comment]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/82053242/63977435-f3df-443d-8bde-5bd084b6eec9)

**Comment by benedictvscriticus** [comment]
@memosys that works!
