### ISSUE TITLE
Create flow is crashing on something with `startsWith` for LinkInput

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#171]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/a53c76cf-5578-40ca-8fc0-017854412879)

**Comment by benedictvscriticus** [comment]
This seems to generally pertain to creating escrows. I.e. creating an escrow does not work right now.

**Comment by benedictvscriticus** [comment]
seems resolved for now @scottrepreneur

**Comment by benedictvscriticus** [comment]
@scottrepreneur how are we looking on this?

**Comment by scottrepreneur** [comment]
Pretty sure this is working, give it a shot. We're focused in on #166 & #181. We're seeing some rly funky behavior with the data caching client.

**Comment by benedictvscriticus** [comment]
@scottrepreneur I can confirm that it works.
