### ISSUE TITLE
Cannot lock funds

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#174]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/7903b80e-f3d4-4f1b-8511-dab3deeac1e0)

**Comment by scottrepreneur** [comment]
Is this still true?

**Comment by benedictvscriticus** [comment]
<img width="1422" alt="Screenshot 2024-04-07 at 6 24 22 PM" src="https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/57eaec2d-cb13-48ef-8079-f429a1abfeda">

Yes, still true

**Comment by memosys** [comment]
Not a FE bug @scottrepreneur @benedictvscriticus
