### ISSUE TITLE
No "release in progress" indication if modal was accidentally closed.

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#176]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/e3c33d59-08c1-42e4-a6e7-a2abf397cfaa)

**Comment by memosys** [comment]
I think this should not be an issue now as added  toast  ux!

TODO
- [ ] verify

**Comment by scottrepreneur** [comment]
Similar issue to #177, gonna close as duplicate. We'll need to move this success handler up a couple levels.
