### ISSUE TITLE
Post Tx handler

### ISSUE THREAD

**Issue by scottrepreneur** [SmartInvoiceXYZ/smart-invoice#181]
- [x] Deposit
- [x] Withdraw
- [x] Release
- [x] Lock
- [x] Add Milestones
- [ ] Resolve - stretch goal

**Comment by benedictvscriticus** [comment]
@scottrepreneur what is this about? Is this part of the refactor?

**Comment by scottrepreneur** [comment]
Yeah this was the last "feature" we needed to complete the refactor. Related to a few of the bugs you filed.
- #179 
- #175

**Comment by benedictvscriticus** [comment]
To show the change after the deposit of funds. This needs invalidating the cached data by the libary, which the library does not let us do it. Potential options are switching to a different library (not preferred). Now looking into the exact configuration to find the culprit.

**Comment by benedictvscriticus** [comment]
Revisit end of next week 03/29
