### ISSUE TITLE
An error occurs when finalising invoice creation

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#184]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/5354865b-fe14-473b-8045-2b4d2e32ee4f)

**Comment by benedictvscriticus** [comment]
@scottrepreneur @memosys this is new. Can you confirm that you can reproduce it?

**Comment by memosys** [comment]
Occasional!

**Comment by scottrepreneur** [comment]
Does the transaction succeed here? Can you catch a loom recording with the console window visible when you see this?

**Comment by benedictvscriticus** [comment]
@scottrepreneur I was able to reproduce it. It seems that ankr deprecated their Goerli RPC, but you can find the full loom here. Invoice creation on Gnosis works fine.

https://www.loom.com/share/82501c83a69e4b75ac66c56eed4b44f3?sid=30236a77-b657-4b17-9b81-2c05a647978c

**Comment by scottrepreneur** [comment]
This appears to be goerli related, closing. Please reopen, if occurring on other networks.
