### ISSUE TITLE
I cannot create an invoice with safety valve date <1 month after invoice creation

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#185]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/306bc07f-de2a-4b2c-bbeb-9f4e6beec8da)

**Comment by benedictvscriticus** [comment]
@scottrepreneur not sure whethe this is expected behaviour

**Comment by scottrepreneur** [comment]
this is currently expected, thanks for clarifying. not a hard limit, can reconsider if hear requests from users. it could be adjusted also, but we should recommend it be at least a month out probably.

**Comment by benedictvscriticus** [comment]
Does this functionality need testing? If so, I may want to ask you to temporarily lower it to 1 day.

**Comment by memosys** [comment]
Proposed Solution as discussed with @scottrepreneur 

for dev purpose:  `check NODE_ENV and don't use (some) validations`

**Comment by memosys** [comment]
for prod- 1 month by default and show warning if < 1month and let continue with warning for > 1 week

**Comment by benedictvscriticus** [comment]
@memosys let me know when I can test it
