### ISSUE TITLE
Ensure that the right invoice data is fetched and is displayed **network specific**

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#187]
Invoices are currently not fetched network specific, but displayed irrespective of the network that is connected.

![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/d6003ed7-6f5a-454b-bfc2-f2b0e0a03443)

The expected behaviour is `const { data, error } = await clients[chainId].query({ query });`

**Comment by scottrepreneur** [comment]
Goerli is deprecated. We're moving to Gnosis for testing until we can add sepolia support. Please re-open/expand on this issue if this is being faced on other networks.

**Comment by benedictvscriticus** [comment]
I haven't encountered it on others, but will have a look. Btw is Mumbai also being deprecated?

**Comment by benedictvscriticus** [comment]
<img width="1369" alt="Screenshot 2024-04-07 at 6 17 24 PM" src="https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/ac9495f9-8590-4eee-9658-ee593d273f71">

yep there are still inconsistencies. Funnily enough on Gnosis its the other way around.

**Comment by benedictvscriticus** [comment]
<img width="1406" alt="Screenshot 2024-04-07 at 6 18 16 PM" src="https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/e7a3cea9-e03f-4996-8bab-fe9d894240e3">
 consistent with Polygon

**Comment by benedictvscriticus** [comment]
Actually the bigger issue here might be that all invoices are shown irrespective of the network and sometimes the "no invoices on [NETWORK]" pops up when subgraph takes a second.

**Comment by benedictvscriticus** [comment]
I guess we want one consistent behaviour. Either showing all or showing only network specific ones in a consistent format (on the table).

**Comment by scottrepreneur** [comment]
Yeah we should only show a single network at a time. Is that not your experience here?

**Comment by benedictvscriticus** [comment]
@scottrepreneur, no 
> Is that not your experience here?
While this is the expected behaviour I always see all invoices created irrespective of the network. We can therefore either
1. add a network column to the table (preferred)
2. show only network specific invoices depending on the network that is connected

**Comment by scottrepreneur** [comment]
Thanks for clarifying mate. After briefly checking the code here, we're only supposed to be looking up invoices for one chain at a time here. Let's update this task to ensure we're actually getting the right set of invoices per network here.
```ts
const { data, error } = await clients[chainId].query({ query });
```

**Comment by benedictvscriticus** [comment]
@scottrepreneur @memosys also does not display correctly yet. Am I using the wrong link eh?

https://smart-invoice-dapp-git-154-dapp-refactor-23-smart-invoice.vercel.app/invoices

![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/3874af79-b71a-4921-b809-b15b93a3cd9e)

**Comment by benedictvscriticus** [comment]
@memosys requires hard refresh to work. Is there a way to fix it?

![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/79542fe4-d315-4d38-a0ed-fb5f70092d18)

Also why do I have inconsitencies in name vs. id?

**Comment by memosys** [comment]
> Also why do I have inconsitencies in name vs. id?

Gnosis subgraph is not indexing ipfs/invoice details!

**Comment by benedictvscriticus** [comment]
Could we please then consistently use the abbrev. invoice ID in hex?

**Comment by memosys** [comment]
> Could we please then consistently use the abbrev. invoice ID in hex?

it will not be an issue once subgraph is fixed!

**Comment by benedictvscriticus** [comment]
@memosys will record a loom shortly

**Comment by scottrepreneur** [comment]
I'm able to repro this as well. Switching between Polygon and Gnosis doesn't fully refresh the table view.

**Comment by benedictvscriticus** [comment]
@memosys https://www.loom.com/share/723500a95db5406696fe4d7c1ed585c9?sid=63ac504c-f907-48da-83a8-54b9f2f51da2

**Comment by benedictvscriticus** [comment]
@memosys it also appears when switching from Polygon to Gnosis but less consistently.
