### ISSUE TITLE
After switching network the wrong network screen pops up for a second

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#188]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/ce4ac88b-195e-43ac-bd92-31cd23a7503a)

**Comment by benedictvscriticus** [comment]
Go to 1:40 to see the bug https://www.loom.com/share/af40cc02b2a3494cac40e5e640ea3f71?sid=32ffab7f-751c-4c1c-8526-a34ec3d5fa93

**Comment by scottrepreneur** [comment]
Can we confirm this on develop?

**Comment by benedictvscriticus** [comment]
Resolved
