### ISSUE TITLE
Figure proper fetch methodology; deprecate apollo client!

### ISSUE THREAD

**Issue by wtfsayo** [SmartInvoiceXYZ/smart-invoice#193]
There is slight delay in success toast and invoice data updation on page; 
I think it would auto-fix itself when apollo-client is chopped off!

TODO:
- [ ] Migrate TypeQueries to regulars for `graphql-request` client
- [ ] Replace Existing Hooks/Queries
- [ ] Test All Flows if working
- [ ] Test for delay issues 

Stretch Goal
- [ ] Reduce number of requests with stale time or auto-fetch

**Comment by dan13ram** [comment]
instead of fetching the invoice data all over again, we should rather use something like this that I wrote for character-sheets. 

https://github.com/raid-guild/character-sheets-frontend/blob/main/graphql/sync.ts#L31
