### ISSUE TITLE
Verify that hard refresh upon invoice creation and client deposit is desired behaviour.

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#194]
Consider adding a note "Please refresh the page" otherwise infinite load or no change on the UI.

![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/93fcc45d-58b9-43e6-a6ed-5e4a71c274d5)

![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/7a8138ec-36b8-4f9c-8bd0-36e30f815a33)

**Comment by scottrepreneur** [comment]
- Can you confirm this was fixed with #192 fixes @memosys ?

**Comment by benedictvscriticus** [comment]
@scottrepreneur, should @memosys check this or me?

**Comment by memosys** [comment]
> - Can you confirm this was fixed with #192 fixes @memosys ?

I think so

**Comment by scottrepreneur** [comment]
Ready to get into testing the post TX handlers here @benedictvscriticus. @memosys is circling back to the table and instant create flow. Can close this if we're able to verify or provide repro steps on which case is occurring.

**Comment by memosys** [comment]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/82053242/95b53ce0-894c-471c-aa58-267ba08fb7c7)

added text

**Comment by benedictvscriticus** [comment]
@memosys you got a typo there. How difficult is it to fix? otherwise good to go.

**Comment by scottrepreneur** [comment]
>  you got a typo there. How difficult is it to fix? otherwise good to go.
you're referring to lowercasing the `p`?

**Comment by benedictvscriticus** [comment]
@scottrepreneur yes!

**Comment by memosys** [comment]
> @scottrepreneur yes!

you got it! updated!
