### ISSUE TITLE
If Kleros arbitration is selected, show minimum invoice value threshold disclaimer.

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#202]
minimum is 1,000 USD

**Comment by wtfsayo** [comment]
@benedictvscriticus should we allow kleros if amount is less than 1000 USD or not let them proceed?

**Comment by benedictvscriticus** [comment]
@wtfsayo the minimum amount should USD 1,000, i.e. if the invoice value is below 1000 Kleros should not be displayed.

**Comment by wtfsayo** [comment]
Arbitrator is selected before reaching amount stage @benedictvscriticus !!!

**Comment by benedictvscriticus** [comment]
@wtfsayo then it should be disclaimer and perhaps you can adapt the text in the drop down stating ">1,000 USD - Kleros". Does that work?

**Comment by wtfsayo** [comment]
thanks that helps!
