### ISSUE TITLE
remove typo from loading screen

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#207]
![Image](https://github.com/SmartInvoiceXYZ/smart-invoice/assets/104435781/24345883-d3b9-4b4e-b8d6-2850cb770bc2)

**Comment by memosys** [comment]
what's the typo here? 😅

**Comment by benedictvscriticus** [comment]
@memosys it should be:

> If the invoice does not load, please refresh the browser.
