### ISSUE TITLE
Be consistent in network referencing

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#267]
> We need to be consistent with the network strategy (probably name or integer)

@scottrepreneur suggested

**Comment by dan13ram** [comment]
Currently the URLs for invoices is https://app.smartinvoice.xyz/invoice/4268/0x7d535b498687e0eb8f3f7bfb65729ce36da5ae6a

but `4268` here is very misleading and confusing. 

We should change the URLs to support all of the following for the example of holesky: 

- [ ] 0x4268
- [ ] 17000
- [ ] holesky

Here `holesky` should be the primary display URL.
