### ISSUE TITLE
update Token selection ux

### ISSUE THREAD

**Issue by dan13ram** [SmartInvoiceXYZ/smart-invoice#268]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/f108db00-c21a-4338-a936-6115cebee1cb">

We should have a search input box for the user to search for a particular token using symbol / name. 

Also currently there is no way for the user to verify the token address if they wanted to.

**Comment by scottrepreneur** [comment]
- Curate the token list here against a smaller list of tokens
- Use `react-select` for richer view here. Allow quick search, show contract address context
