### ISSUE TITLE
UX audit: dApp

### ISSUE THREAD

**Issue by CJ-Rose** [SmartInvoiceXYZ/smart-invoice#278]
- remove "Support" link from header and footer
<img width="1461" alt="Screenshot 2024-12-08 at 4 25 15 PM" src="https://github.com/user-attachments/assets/7bbf1157-256c-4fd5-a4f7-f745cbd576c1">

- dashboard UI should have an indicator for invoices that are awaiting funds/in progress/complete, also a "date completed" column
<img width="1461" alt="Screenshot 2024-12-08 at 4 29 43 PM" src="https://github.com/user-attachments/assets/1d00a4a1-1d1e-49fb-89c2-11f2fad70531">

- tooltip reference to "RIP" will be confusing for users outside of RG and should be removed
<img width="1461" alt="Screenshot 2024-12-08 at 4 35 43 PM" src="https://github.com/user-attachments/assets/caf194e5-b0e1-40da-acad-6398b8f5a0c2">

- user is allowed to create an invoice with misaligned dates
<img width="1461" alt="Screenshot 2024-12-08 at 4 38 42 PM" src="https://github.com/user-attachments/assets/2737942c-6051-4a9a-8dfd-a6fe90a2044a">

- arbitration provider selection should describe the consequences of making the wrong selection ( > or <  $1000)
<img width="1461" alt="Screenshot 2024-12-08 at 5 39 29 PM" src="https://github.com/user-attachments/assets/eb8a04bd-359f-4908-9ea0-40721af69e6c">

- the link to Kleros's 'Terms of Service' in step 2 of invoice creation directs to a Google doc, should go here instead : https://docs.smartinvoice.xyz/arbitration/kleros-arbitration
<img width="1461" alt="Screenshot 2024-12-08 at 4 44 11 PM" src="https://github.com/user-attachments/assets/67982e3f-879a-4c52-9bff-74f71fd22f3a">

- supported tokens should be alphabetized, searchable
<img width="1461" alt="Screenshot 2024-12-08 at 4 47 18 PM" src="https://github.com/user-attachments/assets/8753e6b2-f2c4-4fbe-bfe0-4162941d35cf">

- user is allowed to change networks during invoice creation without causing the invoice form to start over 
<img width="1461" alt="Screenshot 2024-12-08 at 4 51 35 PM" src="https://github.com/user-attachments/assets/318fea23-9239-4e17-8b95-0c241b68d9a0">

- invoice creation takes longer than the alert "Waiting for invoice to be indexed by the subgraph" lasts; user is uncertain is tx is still processing. Spinner on blue button could be updated to show processing message.
<img width="1461" alt="Screenshot 2024-12-08 at 4 54 47 PM" src="https://github.com/user-attachments/assets/2337fc87-afb4-443e-8d6a-0842b0b39137">

- provider should not be shown the deposit button
<img width="1461" alt="Screenshot 2024-12-08 at 5 05 08 PM" src="https://github.com/user-attachments/assets/3ef58dae-82f1-48bd-a487-eba79f634034">

- reference to "raid party" should be removed
<img width="1461" alt="Screenshot 2024-12-08 at 5 15 09 PM" src="https://github.com/user-attachments/assets/c2eceeaf-f75d-4224-afac-ee455594ad7c">

- "deposit" button should change to give client the option to tip the provider after all funds have been released
<img width="1461" alt="Screenshot 2024-12-08 at 5 16 37 PM" src="https://github.com/user-attachments/assets/6e956faf-35f8-4933-a47d-a6a651f7a819">

- dashboard does not reflect newly created invoices until manually refreshed
- invoice does not reflect deposits or releases until manually refreshed (client can open deposit and release modal and repeat the same transaction)
- UI message for token release should explicitly say that funds have been sent to the provider's wallet

**Comment by sshmm** [comment]
I'd like to work on this one.
