### ISSUE TITLE
Standardize the metadata json

### ISSUE THREAD

**Issue by dan13ram** [SmartInvoiceXYZ/smart-invoice#43]
Currently the metadata json for name, description, etc is stored in our frontend codebase. 
But we should build a schema and publish it in the docs for openness and clarity.

This will also enable better integration of smart invoices with other dapps or platforms.

**Comment by plor** [comment]
We have some questions on this, will talk to you at some point.

**Comment by plor** [comment]
Estimated at $4000 (40%)

**Comment by dan13ram** [comment]
@plor 
The idea is to enable smart invoices created from other platforms and/or directly via contract interaction to appear on our UI.
Currently the only way for that to work is for the user to follow the json schema commented at https://github.com/raid-guild/smart-invoice/blob/main/packages/dapp/src/utils/ipfs.js#L19

What I would like to see is a published schema somewhere in our docs similar to https://docs.opensea.io/docs/metadata-standards so that users are not limited to our app. 

Also this is an example of a json schema opensea metadata: https://niftyschema.com/opensea.json
Another for token lists (by uniswap): https://github.com/Uniswap/token-lists/blob/main/src/tokenlist.schema.json

IMO it would be nice to publish similar schema json for our smart invoices somewhere (not sure where though)

Then it would be easy for someone else created a new frontend for our smart invoices to use a library like https://ajv.js.org/ to validate the metadata with our schema before putting it onchain.

Hope that clarifies!
